#pragma once
/*
   This file has been generated by IDA.
   It contains local type definitions from
   the type library 'BNSR_20210511.exe'
*/

#define __int8 char
#define __int16 short
#define __int32 int
#define __int64 long long

#pragma region Data::Skillshow3
struct _DrEl;

/* 314352 */
struct $C581464128C5CCB93BC7E58F8C96B5BA
{
	int id;
	char variation_id;
	__int16 skillskin_id;
};

/* 314353 */
union Data_Skillshow3Record_Key
{
	unsigned __int64 key;
	$C581464128C5CCB93BC7E58F8C96B5BA __s1;
};

/* 192433 */
struct DrEl
{
	char type;
	__int16 subtype;
	unsigned __int16 size;
};

/* 604169 */
//typedef unsigned __int16 wchar_t;

/* 314354 */
const struct __declspec(align(4)) Data_Skillshow3Record : DrEl
{
  __declspec(align(4)) Data_Skillshow3Record_Key key;
  bool play_player_show;
  bool force_play_hit_show;
  __declspec(align(4)) wchar_t* player_cast_show;
  wchar_t* player_exec_show_1;
  wchar_t* player_exec_show_2;
  wchar_t* player_exec_show_3;
  wchar_t* player_exec_show_4;
  wchar_t* player_exec_show_5;
  wchar_t* player_fire_show_1;
  wchar_t* player_fire_show_2;
  wchar_t* player_fire_show_3;
  wchar_t* player_fire_show_4;
  wchar_t* player_fire_show_5;
  wchar_t* player_stop_show;
  char chain_type;
  char create_phantom_type;
  char phantom_shoot_type;
  char lyn_phantom_count;
  bool succession_next_skill;
  bool show_key_result_damage_signal;
  __declspec(align(4)) wchar_t* weapon_prefix;
  bool cast_duration_zero_show_off;
  bool range_decal;
  bool use_berserk_range_decal;
  __declspec(align(2)) wchar_t* cast_show;
  bool exec_show_play_end;
  __declspec(align(4)) wchar_t* decal_show_1;
  wchar_t* fire_show_1;
  wchar_t* fire_miss_show_1;
  wchar_t* exec_show_1;
  wchar_t* exec_hit_show_1;
  wchar_t* exec_immune_show_1;
  wchar_t* exec_dodge_show_1;
  wchar_t* exec_parry_show_1;
  wchar_t* exec_bounce_show_1;
  wchar_t* exec_bounce_caster_show_1;
  wchar_t* exec_counter_show_1;
  wchar_t* exec_critical_show_1;
  wchar_t* return_show_1;
  wchar_t* decal_show_2;
  wchar_t* fire_show_2;
  wchar_t* fire_miss_show_2;
  wchar_t* exec_show_2;
  wchar_t* exec_hit_show_2;
  wchar_t* exec_immune_show_2;
  wchar_t* exec_dodge_show_2;
  wchar_t* exec_parry_show_2;
  wchar_t* exec_bounce_show_2;
  wchar_t* exec_bounce_caster_show_2;
  wchar_t* exec_counter_show_2;
  wchar_t* exec_critical_show_2;
  wchar_t* return_show_2;
  wchar_t* decal_show_3;
  wchar_t* fire_show_3;
  wchar_t* fire_miss_show_3;
  wchar_t* exec_show_3;
  wchar_t* exec_hit_show_3;
  wchar_t* exec_immune_show_3;
  wchar_t* exec_dodge_show_3;
  wchar_t* exec_parry_show_3;
  wchar_t* exec_bounce_show_3;
  wchar_t* exec_bounce_caster_show_3;
  wchar_t* exec_counter_show_3;
  wchar_t* exec_critical_show_3;
  wchar_t* return_show_3;
  wchar_t* decal_show_4;
  wchar_t* fire_show_4;
  wchar_t* fire_miss_show_4;
  wchar_t* exec_show_4;
  wchar_t* exec_hit_show_4;
  wchar_t* exec_immune_show_4;
  wchar_t* exec_dodge_show_4;
  wchar_t* exec_parry_show_4;
  wchar_t* exec_bounce_show_4;
  wchar_t* exec_bounce_caster_show_4;
  wchar_t* exec_counter_show_4;
  wchar_t* exec_critical_show_4;
  wchar_t* return_show_4;
  wchar_t* decal_show_5;
  wchar_t* fire_show_5;
  wchar_t* fire_miss_show_5;
  wchar_t* exec_show_5;
  wchar_t* exec_hit_show_5;
  wchar_t* exec_immune_show_5;
  wchar_t* exec_dodge_show_5;
  wchar_t* exec_parry_show_5;
  wchar_t* exec_bounce_show_5;
  wchar_t* exec_bounce_caster_show_5;
  wchar_t* exec_counter_show_5;
  wchar_t* exec_critical_show_5;
  wchar_t* return_show_5;
  wchar_t* finish_show;
  wchar_t* bomb_show;
  wchar_t* cancel_show;
  wchar_t* stop_show;
  wchar_t* triggered_show;
  wchar_t* trigger_cast_show;
  wchar_t* triggered_enemy_show;
  wchar_t* trigger_show;
  wchar_t* trigger_hit_show;
  wchar_t* trigger_immune_show;
  wchar_t* trigger_dodge_show;
  wchar_t* trigger_parry_show;
  wchar_t* trigger_bounce_show;
  wchar_t* trigger_counter_show;
  wchar_t* trigger_critical_show;
  wchar_t* skill_skin_desc;
};

/* 192875 */
struct __declspec(align(4)) DrRecordPtr
{
	_DrEl* _record;
	int _cacheChunkIndex;
};

/* 314355 */
struct __declspec(align(4)) Data_Skillshow3RecordPtr : DrRecordPtr
{
	__unaligned __declspec(align(1)) const Data_Skillshow3Record* _debug;
	bool _makeCopy;
};

/* 192523 */
struct _DrEl
{
	DrEl* _el;
};
#pragma endregion


enum SkillFlowCode
{
    G_SKILLFLOWCODE_CAST = 0,
    G_SKILLFLOWCODE_FIRE = 1,
    G_SKILLFLOWCODE_FIRE_FAIL = 2,
    G_SKILLFLOWCODE_FIRE_MISS = 3,
    G_SKILLFLOWCODE_EXEC = 4,
    G_SKILLFLOWCODE_EXEC_INTERVAL = 5,
    G_SKILLFLOWCODE_EXEC_FAIL = 6,
    G_SKILLFLOWCODE_RETURN = 7,
    G_SKILLFLOWCODE_FINISH = 8,
    G_SKILLFLOWCODE_CANCEL = 9,
    G_SKILLFLOWCODE_TRIGGERED = 10
};
enum SkillHitCode : __int32
{
    G_SKILLHITCODE_HIT = 0x0,
    G_SKILLHITCODE_MISS = 0x1,
    G_SKILLHITCODE_DODGE = 0x2,
    G_SKILLHITCODE_PARRY = 0x3,
    G_SKILLHITCODE_PERFECT_PARRY = 0x4,
    G_SKILLHITCODE_BOUNCE = 0x5,
    G_SKILLHITCODE_COUNTER = 0x6,
    G_SKILLHITCODE_CRITICAL_HIT = 0x7,
};
enum ESHOW_SIGNAL_TYPE : __int32
{
    SGT_None = 0x0,
    SGT_Miss_Player = 0x1,
    SGT_Miss_Summon = 0x2,
    SGT_Miss_Enemy = 0x3,
    SGT_Miss_TEnemy = 0x4,
    SGT_Dodge_Player = 0x5,
    SGT_Dodge_Summon = 0x6,
    SGT_Dodge_Enemy = 0x7,
    SGT_Dodge_TEnemy = 0x8,
    SGT_Counter_Player = 0x9,
    SGT_Counter_Summon = 0xA,
    SGT_Counter_Enemy = 0xB,
    SGT_Counter_TEnemy = 0xC,
    SGT_PerParry_Player = 0xD,
    SGT_PerParry_Summon = 0xE,
    SGT_PerParry_Enemy = 0xF,
    SGT_PerParry_TEnemy = 0x10,
    SGT_Parry_Player = 0x11,
    SGT_Parry_Summon = 0x12,
    SGT_Parry_Enemy = 0x13,
    SGT_Parry_TEnemy = 0x14,
    SGT_Hit_Player = 0x15,
    SGT_Hit_Summon = 0x16,
    SGT_Hit_Enemy = 0x17,
    SGT_Hit_TEnemy = 0x18,
    SGT_CriHit_Player = 0x19,
    SGT_CriHit_Summon = 0x1A,
    SGT_CriHit_Enemy = 0x1B,
    SGT_CriHit_TEnemy = 0x1C,
    SGT_Heal_Player = 0x1D,
    SGT_Heal_Summon = 0x1E,
    SGT_Heal_Enemy = 0x1F,
    SGT_Heal_TEnemy = 0x20,
    SGT_CriHeal_Player = 0x21,
    SGT_CriHeal_Summon = 0x22,
    SGT_CriHeal_Enemy = 0x23,
    SGT_CriHeal_TEnemy = 0x24,
    SGT_Immune_Player = 0x25,
    SGT_Immune_Summon = 0x26,
    SGT_Immune_Enemy = 0x27,
    SGT_Immune_TEnemy = 0x28,
    SGT_Bump_Player = 0x29,
    SGT_Bump_Summon = 0x2A,
    SGT_Bump_Enemy = 0x2B,
    SGT_Bump_TEnemy = 0x2C,
    SGT_Bounce_Player = 0x2D,
    SGT_Bounce_Summon = 0x2E,
    SGT_Bounce_Enemy = 0x2F,
    SGT_Bounce_TEnemy = 0x30,
    SGT_HPHeal_Player = 0x31,
    SGT_HPHeal_Summon = 0x32,
    SGT_HPHeal_Enemy = 0x33,
    SGT_HPHeal_TEnemy = 0x34,
    SGT_CriHPHeal_Player = 0x35,
    SGT_CriHPHeal_Summon = 0x36,
    SGT_CriHPHeal_Enemy = 0x37,
    SGT_CriHPHeal_TEnemy = 0x38,
    SGT_IntHPHeal_Player = 0x39,
    SGT_IntHPHeal_Summon = 0x3A,
    SGT_IntHPHeal_Enemy = 0x3B,
    SGT_IntHPHeal_TEnemy = 0x3C,
    SGT_FIGHTHeal_Player = 0x3D,
    SGT_FIGHTHeal_Summon = 0x3E,
    SGT_FIGHTHeal_Enemy = 0x3F,
    SGT_FIGHTHeal_TEnemy = 0x40,
    SGT_FIGHTCriHeal_Player = 0x41,
    SGT_FIGHTCriHeal_Summon = 0x42,
    SGT_FIGHTCriHeal_Enemy = 0x43,
    SGT_FIGHTCriHeal_TEnemy = 0x44,
    SGT_FIGHTIntHeal_Player = 0x45,
    SGT_FIGHTIntHeal_Summon = 0x46,
    SGT_FIGHTIntHeal_Enemy = 0x47,
    SGT_FIGHTIntHeal_TEnemy = 0x48,
    SGT_FIGHTDamage_Player = 0x49,
    SGT_FIGHTDamage_Summon = 0x4A,
    SGT_FIGHTDamage_Enemy = 0x4B,
    SGT_FIGHTDamage_TEnemy = 0x4C,
    SGT_CHAKRAHeal_Player = 0x4D,
    SGT_CHAKRAHeal_Summon = 0x4E,
    SGT_CHAKRAHeal_Enemy = 0x4F,
    SGT_CHAKRAHeal_TEnemy = 0x50,
    SGT_CHAKRACriHeal_Player = 0x51,
    SGT_CHAKRACriHeal_Summon = 0x52,
    SGT_CHAKRACriHeal_Enemy = 0x53,
    SGT_CHAKRACriHeal_TEnemy = 0x54,
    SGT_CHAKRAIntHeal_Player = 0x55,
    SGT_CHAKRAIntHeal_Summon = 0x56,
    SGT_CHAKRAIntHeal_Enemy = 0x57,
    SGT_CHAKRAIntHeal_TEnemy = 0x58,
    SGT_CHAKRADamage_Player = 0x59,
    SGT_CHAKRADamage_Summon = 0x5A,
    SGT_CHAKRADamage_Enemy = 0x5B,
    SGT_CHAKRADamage_TEnemy = 0x5C,
    SGT_SWORDHeal_Player = 0x5D,
    SGT_SWORDHeal_Summon = 0x5E,
    SGT_SWORDHeal_Enemy = 0x5F,
    SGT_SWORDHeal_TEnemy = 0x60,
    SGT_SWORDCriHeal_Player = 0x61,
    SGT_SWORDCriHeal_Summon = 0x62,
    SGT_SWORDCriHeal_Enemy = 0x63,
    SGT_SWORDCriHeal_TEnemy = 0x64,
    SGT_SWORDIntHeal_Player = 0x65,
    SGT_SWORDIntHeal_Summon = 0x66,
    SGT_SWORDIntHeal_Enemy = 0x67,
    SGT_SWORDIntHeal_TEnemy = 0x68,
    SGT_SWORDDamage_Player = 0x69,
    SGT_SWORDDamage_Summon = 0x6A,
    SGT_SWORDDamage_Enemy = 0x6B,
    SGT_SWORDDamage_TEnemy = 0x6C,
    SGT_INTFORCEHeal_Player = 0x6D,
    SGT_INTFORCEHeal_Summon = 0x6E,
    SGT_INTFORCEHeal_Enemy = 0x6F,
    SGT_INTFORCEHeal_TEnemy = 0x70,
    SGT_INTFORCECriHeal_Player = 0x71,
    SGT_INTFORCECriHeal_Summon = 0x72,
    SGT_INTFORCECriHeal_Enemy = 0x73,
    SGT_INTFORCECriHeal_TEnemy = 0x74,
    SGT_INTFORCEIntHeal_Player = 0x75,
    SGT_INTFORCEIntHeal_Summon = 0x76,
    SGT_INTFORCEIntHeal_Enemy = 0x77,
    SGT_INTFORCEIntHeal_TEnemy = 0x78,
    SGT_INTFORCEDamage_Player = 0x79,
    SGT_INTFORCEDamage_Summon = 0x7A,
    SGT_INTFORCEDamage_Enemy = 0x7B,
    SGT_INTFORCEDamage_TEnemy = 0x7C,
    SGT_ANGERHeal_Player = 0x7D,
    SGT_ANGERHeal_Summon = 0x7E,
    SGT_ANGERHeal_Enemy = 0x7F,
    SGT_ANGERHeal_TEnemy = 0x80,
    SGT_ANGERCriHeal_Player = 0x81,
    SGT_ANGERCriHeal_Summon = 0x82,
    SGT_ANGERCriHeal_Enemy = 0x83,
    SGT_ANGERCriHeal_TEnemy = 0x84,
    SGT_ANGERIntHeal_Player = 0x85,
    SGT_ANGERIntHeal_Summon = 0x86,
    SGT_ANGERIntHeal_Enemy = 0x87,
    SGT_ANGERIntHeal_TEnemy = 0x88,
    SGT_ANGERDamage_Player = 0x89,
    SGT_ANGERDamage_Summon = 0x8A,
    SGT_ANGERDamage_Enemy = 0x8B,
    SGT_ANGERDamage_TEnemy = 0x8C,
    SGT_FoodHP_Player = 0x8D,
    SGT_FoodHP_Summon = 0x8E,
    SGT_FoodHP_Enemy = 0x8F,
    SGT_FoodHP_TEnemy = 0x90,
    SGT_INTFORCEFoodHP_Player = 0x91,
    SGT_INTFORCEFoodHP_Summon = 0x92,
    SGT_INTFORCEFoodHP_Enemy = 0x93,
    SGT_INTFORCEFoodHP_TEnemy = 0x94,
    SGT_ANGERFoodHP_Player = 0x95,
    SGT_ANGERFoodHP_Summon = 0x96,
    SGT_ANGERFoodHP_Enemy = 0x97,
    SGT_ANGERFoodHP_TEnemy = 0x98,
    SGT_Down_Player = 0x99,
    SGT_Down_Summon = 0x9A,
    SGT_Down_Enemy = 0x9B,
    SGT_Down_TEnemy = 0x9C,
    SGT_Midair1_Player = 0x9D,
    SGT_Midair1_Summon = 0x9E,
    SGT_Midair1_Enemy = 0x9F,
    SGT_Midair1_TEnemy = 0xA0,
    SGT_Midair2_Player = 0xA1,
    SGT_Midair2_Summon = 0xA2,
    SGT_Midair2_Enemy = 0xA3,
    SGT_Midair2_TEnemy = 0xA4,
    SGT_Midair3_Player = 0xA5,
    SGT_Midair3_Summon = 0xA6,
    SGT_Midair3_Enemy = 0xA7,
    SGT_Midair3_TEnemy = 0xA8,
    SGT_Stun_Player = 0xA9,
    SGT_Stun_Summon = 0xAA,
    SGT_Stun_Enemy = 0xAB,
    SGT_Stun_TEnemy = 0xAC,
    SGT_Knockback_Player = 0xAD,
    SGT_Knockback_Summon = 0xAE,
    SGT_Knockback_Enemy = 0xAF,
    SGT_Knockback_TEnemy = 0xB0,
    SGT_Castcancel_Player = 0xB1,
    SGT_Castcancel_Summon = 0xB2,
    SGT_Castcancel_Enemy = 0xB3,
    SGT_Castcancel_TEnemy = 0xB4,
    SGT_Silent_Player = 0xB5,
    SGT_Silent_Summon = 0xB6,
    SGT_Silent_Enemy = 0xB7,
    SGT_Silent_TEnemy = 0xB8,
    SGT_Kneel_Player = 0xB9,
    SGT_Kneel_Summon = 0xBA,
    SGT_Kneel_Enemy = 0xBB,
    SGT_Kneel_TEnemy = 0xBC,
    SGT_Swoon_Player = 0xBD,
    SGT_Swoon_Summon = 0xBE,
    SGT_Swoon_Enemy = 0xBF,
    SGT_Swoon_TEnemy = 0xC0,
    SGT_Knockback2_Player = 0xC1,
    SGT_Knockback2_Summon = 0xC2,
    SGT_Knockback2_Enemy = 0xC3,
    SGT_Knockback2_TEnemy = 0xC4,
    SGT_Ruinphantom_Player = 0xC5,
    SGT_Ruinphantom_Summon = 0xC6,
    SGT_Ruinphantom_Enemy = 0xC7,
    SGT_Ruinphantom_TEnemy = 0xC8,
    SGT_Exp_Player = 0xC9,
    SGT_Exp_Summon = 0xCA,
    SGT_Exp_Enemy = 0xCB,
    SGT_Exp_TEnemy = 0xCC,
    SGT_DownImmune_Player = 0xCD,
    SGT_DownImmune_Summon = 0xCE,
    SGT_DownImmune_Enemy = 0xCF,
    SGT_DownImmune_TEnemy = 0xD0,
    SGT_Midair1Immune_Player = 0xD1,
    SGT_Midair1Immune_Summon = 0xD2,
    SGT_Midair1Immune_Enemy = 0xD3,
    SGT_Midair1Immune_TEnemy = 0xD4,
    SGT_Midair2Immune_Player = 0xD5,
    SGT_Midair2Immune_Summon = 0xD6,
    SGT_Midair2Immune_Enemy = 0xD7,
    SGT_Midair2Immune_TEnemy = 0xD8,
    SGT_Midair3Immune_Player = 0xD9,
    SGT_Midair3Immune_Summon = 0xDA,
    SGT_Midair3Immune_Enemy = 0xDB,
    SGT_Midair3Immune_TEnemy = 0xDC,
    SGT_StunImmune_Player = 0xDD,
    SGT_StunImmune_Summon = 0xDE,
    SGT_StunImmune_Enemy = 0xDF,
    SGT_StunImmune_TEnemy = 0xE0,
    SGT_KneelImmune_Player = 0xE1,
    SGT_KneelImmune_Summon = 0xE2,
    SGT_KneelImmune_Enemy = 0xE3,
    SGT_KneelImmune_TEnemy = 0xE4,
    SGT_SwoonImmune_Player = 0xE5,
    SGT_SwoonImmune_Summon = 0xE6,
    SGT_SwoonImmune_Enemy = 0xE7,
    SGT_SwoonImmune_TEnemy = 0xE8,
    SGT_DamageCounter_Player = 0xE9,
    SGT_DamageCounter_Summon = 0xEA,
    SGT_DamageCounter_Enemy = 0xEB,
    SGT_DamageCounter_TEnemy = 0xEC,
    SGT_VitExp_Player = 0xED,
    SGT_VitExp_Summon = 0xEE,
    SGT_VitExp_Enemy = 0xEF,
    SGT_VitExp_TEnemy = 0xF0,
    SGT_TirExp_Player = 0xF1,
    SGT_TirExp_Summon = 0xF2,
    SGT_TirExp_Enemy = 0xF3,
    SGT_TirExp_TEnemy = 0xF4,
    SGT_Soul_Player = 0xF5,
    SGT_Soul_Summon = 0xF6,
    SGT_Soul_Enemy = 0xF7,
    SGT_Soul_TEnemy = 0xF8,
    SGT_SoulBonus_Player = 0xF9,
    SGT_SoulBonus_Summon = 0xFA,
    SGT_SoulBonus_Enemy = 0xFB,
    SGT_SoulBonus_TEnemy = 0xFC,
    SGT_ExpBonus_Player = 0xFD,
    SGT_ExpBonus_Summon = 0xFE,
    SGT_ExpBonus_Enemy = 0xFF,
    SGT_ExpBonus_TEnemy = 0x100,
    SGT_MasteryExp_Player = 0x101,
    SGT_MasteryExp_Summon = 0x102,
    SGT_MasteryExp_Enemy = 0x103,
    SGT_MasteryExp_TEnemy = 0x104,
    SGT_JiokdoSoul_Player = 0x105,
    SGT_JiokdoSoul_Summon = 0x106,
    SGT_JiokdoSoul_Enemy = 0x107,
    SGT_JiokdoSoul_TEnemy = 0x108,
    SGT_HeartHeal_Player = 0x109,
    SGT_HeartHeal_Summon = 0x10A,
    SGT_HeartHeal_Enemy = 0x10B,
    SGT_HeartHeal_TEnemy = 0x10C,
    SGT_HeartBreak_Player = 0x10D,
    SGT_HeartBreak_Summon = 0x10E,
    SGT_HeartBreak_Enemy = 0x10F,
    SGT_HeartBreak_TEnemy = 0x110,
    SGT_KnockbackImmune_Player = 0x111,
    SGT_KnockbackImmune_Summon = 0x112,
    SGT_KnockbackImmune_Enemy = 0x113,
    SGT_KnockbackImmune_TEnemy = 0x114,
    SGT_DamagePerParry_Player = 0x115,
    SGT_DamagePerParry_Summon = 0x116,
    SGT_DamagePerParry_Enemy = 0x117,
    SGT_DamagePerParry_TEnemy = 0x118,
    SGT_DOT_Player = 0x119,
    SGT_DOT_Summon = 0x11A,
    SGT_DOT_Enemy = 0x11B,
    SGT_DOT_TEnemy = 0x11C,
    SGT_BigHit_Player = 0x11D,
    SGT_BigHit_Summon = 0x11E,
    SGT_BigHit_Enemy = 0x11F,
    SGT_BigHit_TEnemy = 0x120,
    SGT_BigCriHit_Player = 0x121,
    SGT_BigCriHit_Summon = 0x122,
    SGT_BigCriHit_Enemy = 0x123,
    SGT_BigCriHit_TEnemy = 0x124,
    SGT_GoldMoney_Player = 0x125,
    SGT_GoldMoney_Summon = 0x126,
    SGT_GoldMoney_Enemy = 0x127,
    SGT_GoldMoney_TEnemy = 0x128,
    SGT_SilverMoney_Player = 0x129,
    SGT_SilverMoney_Summon = 0x12A,
    SGT_SilverMoney_Enemy = 0x12B,
    SGT_SilverMoney_TEnemy = 0x12C,
    SGT_BronzeMoney_Player = 0x12D,
    SGT_BronzeMoney_Summon = 0x12E,
    SGT_BronzeMoney_Enemy = 0x12F,
    SGT_BronzeMoney_TEnemy = 0x130,
    SGT_SoulSec_Player = 0x131,
    SGT_SoulSec_Summon = 0x132,
    SGT_SoulSec_Enemy = 0x133,
    SGT_SoulSec_TEnemy = 0x134,
    SGT_SoulThr_Player = 0x135,
    SGT_SoulThr_Summon = 0x136,
    SGT_SoulThr_Enemy = 0x137,
    SGT_SoulThr_TEnemy = 0x138,
    SGT_Score_Player = 0x139,
    SGT_Score_Summon = 0x13A,
    SGT_Score_Enemy = 0x13B,
    SGT_Score_TEnemy = 0x13C,
    SGT_DuelPoint_Player = 0x13D,
    SGT_DuelPoint_Summon = 0x13E,
    SGT_DuelPoint_Enemy = 0x13F,
    SGT_DuelPoint_TEnemy = 0x140,
    SGT_BattlePoint_Player = 0x141,
    SGT_BattlePoint_Summon = 0x142,
    SGT_BattlePoint_Enemy = 0x143,
    SGT_BattlePoint_TEnemy = 0x144,
    SGT_PlayPoint_Player = 0x145,
    SGT_PlayPoint_Summon = 0x146,
    SGT_PlayPoint_Enemy = 0x147,
    SGT_PlayPoint_TEnemy = 0x148,
    SGT_LifeContentsPoint_Player = 0x149,
    SGT_LifeContentsPoint_Summon = 0x14A,
    SGT_LifeContentsPoint_Enemy = 0x14B,
    SGT_LifeContentsPoint_TEnemy = 0x14C,
    SGT_QuestRewardFactionScore_Player = 0x14D,
    SGT_QuestRewardFactionScore_Summon = 0x14E,
    SGT_QuestRewardFactionScore_Enemy = 0x14F,
    SGT_QuestRewardFactionScore_TEnemy = 0x150,
    SGT_GUARDGAUGEHit_Player = 0x151,
    SGT_GUARDGAUGEHit_Summon = 0x152,
    SGT_GUARDGAUGEHit_Enemy = 0x153,
    SGT_GUARDGAUGEHit_TEnemy = 0x154,
    SGT_GUARDGAUGEHeal_Player = 0x155,
    SGT_GUARDGAUGEHeal_Summon = 0x156,
    SGT_GUARDGAUGEHeal_Enemy = 0x157,
    SGT_GUARDGAUGEHeal_TEnemy = 0x158,
    SGT_Miss_PartyPlayer = 0x159,
    SGT_Miss_PartySummon = 0x15A,
    SGT_Miss_PartyEnemy = 0x15B,
    SGT_Miss_PartyTEnemy = 0x15C,
    SGT_Dodge_PartyPlayer = 0x15D,
    SGT_Dodge_PartySummon = 0x15E,
    SGT_Dodge_PartyEnemy = 0x15F,
    SGT_Dodge_PartyTEnemy = 0x160,
    SGT_Counter_PartyPlayer = 0x161,
    SGT_Counter_PartySummon = 0x162,
    SGT_Counter_PartyEnemy = 0x163,
    SGT_Counter_PartyTEnemy = 0x164,
    SGT_PerParry_PartyPlayer = 0x165,
    SGT_PerParry_PartySummon = 0x166,
    SGT_PerParry_PartyEnemy = 0x167,
    SGT_PerParry_PartyTEnemy = 0x168,
    SGT_Parry_PartyPlayer = 0x169,
    SGT_Parry_PartySummon = 0x16A,
    SGT_Parry_PartyEnemy = 0x16B,
    SGT_Parry_PartyTEnemy = 0x16C,
    SGT_Hit_PartyPlayer = 0x16D,
    SGT_Hit_PartySummon = 0x16E,
    SGT_Hit_PartyEnemy = 0x16F,
    SGT_Hit_PartyTEnemy = 0x170,
    SGT_CriHit_PartyPlayer = 0x171,
    SGT_CriHit_PartySummon = 0x172,
    SGT_CriHit_PartyEnemy = 0x173,
    SGT_CriHit_PartyTEnemy = 0x174,
    SGT_Heal_PartyPlayer = 0x175,
    SGT_Heal_PartySummon = 0x176,
    SGT_Heal_PartyEnemy = 0x177,
    SGT_Heal_PartyTEnemy = 0x178,
    SGT_CriHeal_PartyPlayer = 0x179,
    SGT_CriHeal_PartySummon = 0x17A,
    SGT_CriHeal_PartyEnemy = 0x17B,
    SGT_CriHeal_PartyTEnemy = 0x17C,
    SGT_Immune_PartyPlayer = 0x17D,
    SGT_Immune_PartySummon = 0x17E,
    SGT_Immune_PartyEnemy = 0x17F,
    SGT_Immune_PartyTEnemy = 0x180,
    SGT_Bump_PartyPlayer = 0x181,
    SGT_Bump_PartySummon = 0x182,
    SGT_Bump_PartyEnemy = 0x183,
    SGT_Bump_PartyTEnemy = 0x184,
    SGT_Bounce_PartyPlayer = 0x185,
    SGT_Bounce_PartySummon = 0x186,
    SGT_Bounce_PartyEnemy = 0x187,
    SGT_Bounce_PartyTEnemy = 0x188,
    SGT_HPHeal_PartyPlayer = 0x189,
    SGT_HPHeal_PartySummon = 0x18A,
    SGT_HPHeal_PartyEnemy = 0x18B,
    SGT_HPHeal_PartyTEnemy = 0x18C,
    SGT_CriHPHeal_PartyPlayer = 0x18D,
    SGT_CriHPHeal_PartySummon = 0x18E,
    SGT_CriHPHeal_PartyEnemy = 0x18F,
    SGT_CriHPHeal_PartyTEnemy = 0x190,
    SGT_IntHPHeal_PartyPlayer = 0x191,
    SGT_IntHPHeal_PartySummon = 0x192,
    SGT_IntHPHeal_PartyEnemy = 0x193,
    SGT_IntHPHeal_PartyTEnemy = 0x194,
    SGT_FIGHTHeal_PartyPlayer = 0x195,
    SGT_FIGHTHeal_PartySummon = 0x196,
    SGT_FIGHTHeal_PartyEnemy = 0x197,
    SGT_FIGHTHeal_PartyTEnemy = 0x198,
    SGT_FIGHTCriHeal_PartyPlayer = 0x199,
    SGT_FIGHTCriHeal_PartySummon = 0x19A,
    SGT_FIGHTCriHeal_PartyEnemy = 0x19B,
    SGT_FIGHTCriHeal_PartyTEnemy = 0x19C,
    SGT_FIGHTIntHeal_PartyPlayer = 0x19D,
    SGT_FIGHTIntHeal_PartySummon = 0x19E,
    SGT_FIGHTIntHeal_PartyEnemy = 0x19F,
    SGT_FIGHTIntHeal_PartyTEnemy = 0x1A0,
    SGT_FIGHTDamage_PartyPlayer = 0x1A1,
    SGT_FIGHTDamage_PartySummon = 0x1A2,
    SGT_FIGHTDamage_PartyEnemy = 0x1A3,
    SGT_FIGHTDamage_PartyTEnemy = 0x1A4,
    SGT_CHAKRAHeal_PartyPlayer = 0x1A5,
    SGT_CHAKRAHeal_PartySummon = 0x1A6,
    SGT_CHAKRAHeal_PartyEnemy = 0x1A7,
    SGT_CHAKRAHeal_PartyTEnemy = 0x1A8,
    SGT_CHAKRACriHeal_PartyPlayer = 0x1A9,
    SGT_CHAKRACriHeal_PartySummon = 0x1AA,
    SGT_CHAKRACriHeal_PartyEnemy = 0x1AB,
    SGT_CHAKRACriHeal_PartyTEnemy = 0x1AC,
    SGT_CHAKRAIntHeal_PartyPlayer = 0x1AD,
    SGT_CHAKRAIntHeal_PartySummon = 0x1AE,
    SGT_CHAKRAIntHeal_PartyEnemy = 0x1AF,
    SGT_CHAKRAIntHeal_PartyTEnemy = 0x1B0,
    SGT_CHAKRADamage_PartyPlayer = 0x1B1,
    SGT_CHAKRADamage_PartySummon = 0x1B2,
    SGT_CHAKRADamage_PartyEnemy = 0x1B3,
    SGT_CHAKRADamage_PartyTEnemy = 0x1B4,
    SGT_SWORDHeal_PartyPlayer = 0x1B5,
    SGT_SWORDHeal_PartySummon = 0x1B6,
    SGT_SWORDHeal_PartyEnemy = 0x1B7,
    SGT_SWORDHeal_PartyTEnemy = 0x1B8,
    SGT_SWORDCriHeal_PartyPlayer = 0x1B9,
    SGT_SWORDCriHeal_PartySummon = 0x1BA,
    SGT_SWORDCriHeal_PartyEnemy = 0x1BB,
    SGT_SWORDCriHeal_PartyTEnemy = 0x1BC,
    SGT_SWORDIntHeal_PartyPlayer = 0x1BD,
    SGT_SWORDIntHeal_PartySummon = 0x1BE,
    SGT_SWORDIntHeal_PartyEnemy = 0x1BF,
    SGT_SWORDIntHeal_PartyTEnemy = 0x1C0,
    SGT_SWORDDamage_PartyPlayer = 0x1C1,
    SGT_SWORDDamage_PartySummon = 0x1C2,
    SGT_SWORDDamage_PartyEnemy = 0x1C3,
    SGT_SWORDDamage_PartyTEnemy = 0x1C4,
    SGT_INTFORCEHeal_PartyPlayer = 0x1C5,
    SGT_INTFORCEHeal_PartySummon = 0x1C6,
    SGT_INTFORCEHeal_PartyEnemy = 0x1C7,
    SGT_INTFORCEHeal_PartyTEnemy = 0x1C8,
    SGT_INTFORCECriHeal_PartyPlayer = 0x1C9,
    SGT_INTFORCECriHeal_PartySummon = 0x1CA,
    SGT_INTFORCECriHeal_PartyEnemy = 0x1CB,
    SGT_INTFORCECriHeal_PartyTEnemy = 0x1CC,
    SGT_INTFORCEIntHeal_PartyPlayer = 0x1CD,
    SGT_INTFORCEIntHeal_PartySummon = 0x1CE,
    SGT_INTFORCEIntHeal_PartyEnemy = 0x1CF,
    SGT_INTFORCEIntHeal_PartyTEnemy = 0x1D0,
    SGT_INTFORCEDamage_PartyPlayer = 0x1D1,
    SGT_INTFORCEDamage_PartySummon = 0x1D2,
    SGT_INTFORCEDamage_PartyEnemy = 0x1D3,
    SGT_INTFORCEDamage_PartyTEnemy = 0x1D4,
    SGT_ANGERHeal_PartyPlayer = 0x1D5,
    SGT_ANGERHeal_PartySummon = 0x1D6,
    SGT_ANGERHeal_PartyEnemy = 0x1D7,
    SGT_ANGERHeal_PartyTEnemy = 0x1D8,
    SGT_ANGERCriHeal_PartyPlayer = 0x1D9,
    SGT_ANGERCriHeal_PartySummon = 0x1DA,
    SGT_ANGERCriHeal_PartyEnemy = 0x1DB,
    SGT_ANGERCriHeal_PartyTEnemy = 0x1DC,
    SGT_ANGERIntHeal_PartyPlayer = 0x1DD,
    SGT_ANGERIntHeal_PartySummon = 0x1DE,
    SGT_ANGERIntHeal_PartyEnemy = 0x1DF,
    SGT_ANGERIntHeal_PartyTEnemy = 0x1E0,
    SGT_ANGERDamage_PartyPlayer = 0x1E1,
    SGT_ANGERDamage_PartySummon = 0x1E2,
    SGT_ANGERDamage_PartyEnemy = 0x1E3,
    SGT_ANGERDamage_PartyTEnemy = 0x1E4,
    SGT_FoodHP_PartyPlayer = 0x1E5,
    SGT_FoodHP_PartySummon = 0x1E6,
    SGT_FoodHP_PartyEnemy = 0x1E7,
    SGT_FoodHP_PartyTEnemy = 0x1E8,
    SGT_INTFORCEFoodHP_PartyPlayer = 0x1E9,
    SGT_INTFORCEFoodHP_PartySummon = 0x1EA,
    SGT_INTFORCEFoodHP_PartyEnemy = 0x1EB,
    SGT_INTFORCEFoodHP_PartyTEnemy = 0x1EC,
    SGT_ANGERFoodHP_PartyPlayer = 0x1ED,
    SGT_ANGERFoodHP_PartySummon = 0x1EE,
    SGT_ANGERFoodHP_PartyEnemy = 0x1EF,
    SGT_ANGERFoodHP_PartyTEnemy = 0x1F0,
    SGT_Down_PartyPlayer = 0x1F1,
    SGT_Down_PartySummon = 0x1F2,
    SGT_Down_PartyEnemy = 0x1F3,
    SGT_Down_PartyTEnemy = 0x1F4,
    SGT_Midair1_PartyPlayer = 0x1F5,
    SGT_Midair1_PartySummon = 0x1F6,
    SGT_Midair1_PartyEnemy = 0x1F7,
    SGT_Midair1_PartyTEnemy = 0x1F8,
    SGT_Midair2_PartyPlayer = 0x1F9,
    SGT_Midair2_PartySummon = 0x1FA,
    SGT_Midair2_PartyEnemy = 0x1FB,
    SGT_Midair2_PartyTEnemy = 0x1FC,
    SGT_Midair3_PartyPlayer = 0x1FD,
    SGT_Midair3_PartySummon = 0x1FE,
    SGT_Midair3_PartyEnemy = 0x1FF,
    SGT_Midair3_PartyTEnemy = 0x200,
    SGT_Stun_PartyPlayer = 0x201,
    SGT_Stun_PartySummon = 0x202,
    SGT_Stun_PartyEnemy = 0x203,
    SGT_Stun_PartyTEnemy = 0x204,
    SGT_Knockback_PartyPlayer = 0x205,
    SGT_Knockback_PartySummon = 0x206,
    SGT_Knockback_PartyEnemy = 0x207,
    SGT_Knockback_PartyTEnemy = 0x208,
    SGT_Castcancel_PartyPlayer = 0x209,
    SGT_Castcancel_PartySummon = 0x20A,
    SGT_Castcancel_PartyEnemy = 0x20B,
    SGT_Castcancel_PartyTEnemy = 0x20C,
    SGT_Silent_PartyPlayer = 0x20D,
    SGT_Silent_PartySummon = 0x20E,
    SGT_Silent_PartyEnemy = 0x20F,
    SGT_Silent_PartyTEnemy = 0x210,
    SGT_Kneel_PartyPlayer = 0x211,
    SGT_Kneel_PartySummon = 0x212,
    SGT_Kneel_PartyEnemy = 0x213,
    SGT_Kneel_PartyTEnemy = 0x214,
    SGT_Swoon_PartyPlayer = 0x215,
    SGT_Swoon_PartySummon = 0x216,
    SGT_Swoon_PartyEnemy = 0x217,
    SGT_Swoon_PartyTEnemy = 0x218,
    SGT_Knockback2_PartyPlayer = 0x219,
    SGT_Knockback2_PartySummon = 0x21A,
    SGT_Knockback2_PartyEnemy = 0x21B,
    SGT_Knockback2_PartyTEnemy = 0x21C,
    SGT_Ruinphantom_PartyPlayer = 0x21D,
    SGT_Ruinphantom_PartySummon = 0x21E,
    SGT_Ruinphantom_PartyEnemy = 0x21F,
    SGT_Ruinphantom_PartyTEnemy = 0x220,
    SGT_Exp_PartyPlayer = 0x221,
    SGT_Exp_PartySummon = 0x222,
    SGT_Exp_PartyEnemy = 0x223,
    SGT_Exp_PartyTEnemy = 0x224,
    SGT_DownImmune_PartyPlayer = 0x225,
    SGT_DownImmune_PartySummon = 0x226,
    SGT_DownImmune_PartyEnemy = 0x227,
    SGT_DownImmune_PartyTEnemy = 0x228,
    SGT_Midair1Immune_PartyPlayer = 0x229,
    SGT_Midair1Immune_PartySummon = 0x22A,
    SGT_Midair1Immune_PartyEnemy = 0x22B,
    SGT_Midair1Immune_PartyTEnemy = 0x22C,
    SGT_Midair2Immune_PartyPlayer = 0x22D,
    SGT_Midair2Immune_PartySummon = 0x22E,
    SGT_Midair2Immune_PartyEnemy = 0x22F,
    SGT_Midair2Immune_PartyTEnemy = 0x230,
    SGT_Midair3Immune_PartyPlayer = 0x231,
    SGT_Midair3Immune_PartySummon = 0x232,
    SGT_Midair3Immune_PartyEnemy = 0x233,
    SGT_Midair3Immune_PartyTEnemy = 0x234,
    SGT_StunImmune_PartyPlayer = 0x235,
    SGT_StunImmune_PartySummon = 0x236,
    SGT_StunImmune_PartyEnemy = 0x237,
    SGT_StunImmune_PartyTEnemy = 0x238,
    SGT_KneelImmune_PartyPlayer = 0x239,
    SGT_KneelImmune_PartySummon = 0x23A,
    SGT_KneelImmune_PartyEnemy = 0x23B,
    SGT_KneelImmune_PartyTEnemy = 0x23C,
    SGT_SwoonImmune_PartyPlayer = 0x23D,
    SGT_SwoonImmune_PartySummon = 0x23E,
    SGT_SwoonImmune_PartyEnemy = 0x23F,
    SGT_SwoonImmune_PartyTEnemy = 0x240,
    SGT_DamageCounter_PartyPlayer = 0x241,
    SGT_DamageCounter_PartySummon = 0x242,
    SGT_DamageCounter_PartyEnemy = 0x243,
    SGT_DamageCounter_PartyTEnemy = 0x244,
    SGT_VitExp_PartyPlayer = 0x245,
    SGT_VitExp_PartySummon = 0x246,
    SGT_VitExp_PartyEnemy = 0x247,
    SGT_VitExp_PartyTEnemy = 0x248,
    SGT_TirExp_PartyPlayer = 0x249,
    SGT_TirExp_PartySummon = 0x24A,
    SGT_TirExp_PartyEnemy = 0x24B,
    SGT_TirExp_PartyTEnemy = 0x24C,
    SGT_Soul_PartyPlayer = 0x24D,
    SGT_Soul_PartySummon = 0x24E,
    SGT_Soul_PartyEnemy = 0x24F,
    SGT_Soul_PartyTEnemy = 0x250,
    SGT_SoulBonus_PartyPlayer = 0x251,
    SGT_SoulBonus_PartySummon = 0x252,
    SGT_SoulBonus_PartyEnemy = 0x253,
    SGT_SoulBonus_PartyTEnemy = 0x254,
    SGT_ExpBonus_PartyPlayer = 0x255,
    SGT_ExpBonus_PartySummon = 0x256,
    SGT_ExpBonus_PartyEnemy = 0x257,
    SGT_ExpBonus_PartyTEnemy = 0x258,
    SGT_MasteryExp_PartyPlayer = 0x259,
    SGT_MasteryExp_PartySummon = 0x25A,
    SGT_MasteryExp_PartyEnemy = 0x25B,
    SGT_MasteryExp_PartyTEnemy = 0x25C,
    SGT_JiokdoSoul_PartyPlayer = 0x25D,
    SGT_JiokdoSoul_PartySummon = 0x25E,
    SGT_JiokdoSoul_PartyEnemy = 0x25F,
    SGT_JiokdoSoul_PartyTEnemy = 0x260,
    SGT_HeartHeal_PartyPlayer = 0x261,
    SGT_HeartHeal_PartySummon = 0x262,
    SGT_HeartHeal_PartyEnemy = 0x263,
    SGT_HeartHeal_PartyTEnemy = 0x264,
    SGT_HeartBreak_PartyPlayer = 0x265,
    SGT_HeartBreak_PartySummon = 0x266,
    SGT_HeartBreak_PartyEnemy = 0x267,
    SGT_HeartBreak_PartyTEnemy = 0x268,
    SGT_KnockbackImmune_PartyPlayer = 0x269,
    SGT_KnockbackImmune_PartySummon = 0x26A,
    SGT_KnockbackImmune_PartyEnemy = 0x26B,
    SGT_KnockbackImmune_PartyTEnemy = 0x26C,
    SGT_DamagePerParry_PartyPlayer = 0x26D,
    SGT_DamagePerParry_PartySummon = 0x26E,
    SGT_DamagePerParry_PartyEnemy = 0x26F,
    SGT_DamagePerParry_PartyTEnemy = 0x270,
    SGT_DOT_PartyPlayer = 0x271,
    SGT_DOT_PartySummon = 0x272,
    SGT_DOT_PartyEnemy = 0x273,
    SGT_DOT_PartyTEnemy = 0x274,
    SGT_BigHit_PartyPlayer = 0x275,
    SGT_BigHit_PartySummon = 0x276,
    SGT_BigHit_PartyEnemy = 0x277,
    SGT_BigHit_PartyTEnemy = 0x278,
    SGT_BigCriHit_PartyPlayer = 0x279,
    SGT_BigCriHit_PartySummon = 0x27A,
    SGT_BigCriHit_PartyEnemy = 0x27B,
    SGT_BigCriHit_PartyTEnemy = 0x27C,
    SGT_GoldMoney_PartyPlayer = 0x27D,
    SGT_GoldMoney_PartySummon = 0x27E,
    SGT_GoldMoney_PartyEnemy = 0x27F,
    SGT_GoldMoney_PartyTEnemy = 0x280,
    SGT_SilverMoney_PartyPlayer = 0x281,
    SGT_SilverMoney_PartySummon = 0x282,
    SGT_SilverMoney_PartyEnemy = 0x283,
    SGT_SilverMoney_PartyTEnemy = 0x284,
    SGT_BronzeMoney_PartyPlayer = 0x285,
    SGT_BronzeMoney_PartySummon = 0x286,
    SGT_BronzeMoney_PartyEnemy = 0x287,
    SGT_BronzeMoney_PartyTEnemy = 0x288,
    SGT_SoulSec_PartyPlayer = 0x289,
    SGT_SoulSec_PartySummon = 0x28A,
    SGT_SoulSec_PartyEnemy = 0x28B,
    SGT_SoulSec_PartyTEnemy = 0x28C,
    SGT_SoulThr_PartyPlayer = 0x28D,
    SGT_SoulThr_PartySummon = 0x28E,
    SGT_SoulThr_PartyEnemy = 0x28F,
    SGT_SoulThr_PartyTEnemy = 0x290,
    SGT_Score_PartyPlayer = 0x291,
    SGT_Score_PartySummon = 0x292,
    SGT_Score_PartyEnemy = 0x293,
    SGT_Score_PartyTEnemy = 0x294,
    SGT_DuelPoint_PartyPlayer = 0x295,
    SGT_DuelPoint_PartySummon = 0x296,
    SGT_DuelPoint_PartyEnemy = 0x297,
    SGT_DuelPoint_PartyTEnemy = 0x298,
    SGT_BattlePoint_PartyPlayer = 0x299,
    SGT_BattlePoint_PartySummon = 0x29A,
    SGT_BattlePoint_PartyEnemy = 0x29B,
    SGT_BattlePoint_PartyTEnemy = 0x29C,
    SGT_PlayPoint_PartyPlayer = 0x29D,
    SGT_PlayPoint_PartySummon = 0x29E,
    SGT_PlayPoint_PartyEnemy = 0x29F,
    SGT_PlayPoint_PartyTEnemy = 0x2A0,
    SGT_LifeContentsPoint_PartyPlayer = 0x2A1,
    SGT_LifeContentsPoint_PartySummon = 0x2A2,
    SGT_LifeContentsPoint_PartyEnemy = 0x2A3,
    SGT_LifeContentsPoint_PartyTEnemy = 0x2A4,
    SGT_QuestRewardFactionScore_PartyPlayer = 0x2A5,
    SGT_QuestRewardFactionScore_PartySummon = 0x2A6,
    SGT_QuestRewardFactionScore_PartyEnemy = 0x2A7,
    SGT_QuestRewardFactionScore_PartyTEnemy = 0x2A8,
    SGT_GUARDGAUGEHit_PartyPlayer = 0x2A9,
    SGT_GUARDGAUGEHit_PartySummon = 0x2AA,
    SGT_GUARDGAUGEHit_PartyEnemy = 0x2AB,
    SGT_GUARDGAUGEHit_PartyTEnemy = 0x2AC,
    SGT_GUARDGAUGEHeal_PartyPlayer = 0x2AD,
    SGT_GUARDGAUGEHeal_PartySummon = 0x2AE,
    SGT_GUARDGAUGEHeal_PartyEnemy = 0x2AF,
    SGT_GUARDGAUGEHeal_PartyTEnemy = 0x2B0,
    SGT_MAX = 0x2B1,
};



#define EInterface_Handle uintptr_t*
struct PTActiveSkill2_vtbl;
struct PTSkill2
{
    PTActiveSkill2_vtbl* __vftable /*VFT*/;
    unsigned __int64 _caster;
    uintptr_t* _creatureCaster;
    EInterface_Handle _casterHandle;
    EInterface_Handle _targetHandle;
    EInterface_Handle _targetHandle2;
    Data_Skillshow3RecordPtr _showData;
    char _skillInstanceId;
    std::wstring _strWeaponName;
    int _castDelayCounter;
    SkillHitCode _hitResult;
    ESHOW_SIGNAL_TYPE _damageSignalType;
    __int16 _castStepYaw;
    __int16 _castStepRelativeYaw;
};
Sizer<sizeof(PTSkill2)> xd;
static_assert(sizeof(PTSkill2) == 0x70);
struct PTActiveSkill2 : PTSkill2
{
    EInterface_Handle _showStageHandle;
    EInterface_Handle _castDecalHandle;
    EInterface_Handle _skillCastDecalHandle;
    EInterface_Handle _fireInputParamHandle;
    EInterface_Handle _fireOutputParamHandle;
    EInterface_Handle _triggeredshowStageHandle;
    EInterface_Handle _triggerCastshowStageHandle;
    EInterface_Handle _chainshowStageHandle;
    float _decallifeTime;
    EInterface_Handle _decalTargetHandle;
    EInterface_Handle _decalStartParticleHandle;
    EInterface_Handle _decalLoopParticleHandle;
    EInterface_Handle _decalVelocityParticleHandle;
    std::vector<PTSkill2::ResultInputParam*> _resultInputParameterList;
    std::vector<PTSkill2::ResultInputParam*> _resultTriggerInputParameterList;
    bool bIsEgoSkill;
    int _beamFireTargetIndex;
    bool _isCasterLastAnimPause;
    bool _isBoneAttach;
    unsigned __int64 _attachBoneType;
    BPTCreature* _catchCastingTarget;
    PTPhantomWeaponInstance* _phantomWeaponInstance;
    bool _isPlaySkillRangeDecal;
    int _lastRangeDecalShapeType;
};
struct /*VFT*/ PTActiveSkill2_vtbl
{
    void(__fastcall * ~PTSkill2)(PTSkill2* thisptr);
    void(__fastcall* UpdateTarget)(PTSkill2* thisptr);
    void(__fastcall* SetCaster)(PTSkill2* thisptr, BPTCreature*);
    void(__fastcall* Activate)(PTSkill2* thisptr, Data::Skill3RecordPtr*, const char, const unsigned __int64);
    void(__fastcall* Deactivate)(PTSkill2* thisptr);
    void(__fastcall* Cast)(PTSkill2* thisptr, float, const __int16, const __int16);
    void(__fastcall* Fire)(PTSkill2* thisptr, float);
    void(__fastcall* FireMiss)(PTSkill2* thisptr, float);
    void(__fastcall* FireFail)(PTSkill2* thisptr, float);
    void(__fastcall* Exec)(PTSkill2* thisptr, float);
    void(__fastcall* ExecFail)(PTSkill2* thisptr, float);
    void(__fastcall* Return)(PTSkill2* thisptr, float);
    void(__fastcall* Finish)(PTSkill2* thisptr);
    void(__fastcall* Cancel)(PTSkill2* thisptr, float, char);
    void(__fastcall* Triggered)(PTSkill2* thisptr);
    void(__fastcall* CastDelayShow)(PTSkill2* thisptr);
    void(__fastcall* PlayHideShow)(PTSkill2* thisptr, bool, bool);
    SkillResult* SkillResult;
    void(__fastcall* detachBone)(PTSkill2* thisptr, __int64, bool);
    bool(__fastcall* AddDamageOnInputParamsignalType)(PTSkill2* thisptr, __int64, float, ESHOW_SIGNAL_TYPE);
    bool(__fastcall* AddDamageOnInputParamAdditionalSignalType)(PTSkill2* thisptr, __int64, float, ESHOW_SIGNAL_TYPE);
    EInterface_Handle* (__fastcall* GetChainShow)(PTSkill2* thisptr, EInterface_Handle* result);
    void(__fastcall* SetChainshowStageHandleNULL)(PTSkill2* thisptr);
    bool(__fastcall* IsActiveSkill)(PTSkill2* thisptr);
};